version: ''
services:
    mongodb:
        image:mongo
        
        ports:
           - 27017:27017
        environments:
        	- MONGO-INITDB_ROOT_USERNAME=admin
        	- MONGO-INITDB_ROOT_PASSWORD=password
        	
        	
    mongo-express:
        image:mongo-express
        
        ports:
           - 8081:8081
        environments:
        	- ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        	- ME_CONFIG_MONGODB_ADMINPASSWORD=password
        	- ME_CONFIG_MONGODB_SERVER=mongodb
